POST http://localhost:/signIn
Content-Type: application/json

{
  "email" : "sasha.kochedykov@mail.ru",
  "password": "123"
}

###


###
GET http://localhost/users/2/articles
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZSI6IkFETUlOIn0.1Tz-EyU3j-cAnDpqGvOhJI3yPzTYAXfhPWx_y3Y0_gY
###

GET http://localhost/articles/7
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZSI6IkFETUlOIn0.1Tz-EyU3j-cAnDpqGvOhJI3yPzTYAXfhPWx_y3Y0_gY
###

DELETE http://localhost/articles/69
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwicm9sZSI6IkFETUlOIn0.1Tz-EyU3j-cAnDpqGvOhJI3yPzTYAXfhPWx_y3Y0_gY
###
