server:
  port: 1010
zuul:
  routes:
    articles:
      path: /articles-management/**
      serviceId: articles-service

    users:
      path: /users-management/**
      serviceId: users-service

spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url.default: http://localhost:8761/eureka